test:python36:
    image: python:3.6
    script: 
    - pip install -r requirements.txt  
    - py.test -v --cov --pep8

test:miniconda3:
    image: continuumio/miniconda3
    script: 
    - conda env create -f environment.yml
    - source activate fem
    - py.test -v --cov --pep8
