test:python35:
    image: python:3.5
    script: 
    - pip install -r requirements.txt  
    - export PYTHONPATH=../
    - py.test -v --cov

test:python36:
    image: python:3.6
    script: 
    - pip install -r requirements.txt  
    - export PYTHONPATH=../
    - py.test -v --cov

test:anaconda3:
    image: continuumio/anaconda3
    script: 
    - conda install -y pytest-cov
    - export PYTHONPATH=../
    - py.test -v --cov
