language: python
python:
      - "3.4"
      - "3.5"
      - "3.6"
      - "3.6-dev"
      - "3.7-dev"
      - "nightly"
install:
      - pip install -r requirements.txt
script: 
      - pytest -v --cov --pep8
